//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;

    public partial class AttendanceStatu
    {
        public string status_type;
        public string status_code;

        public int status_id { get; set; }
        public string status { get; set; }
    }
}
