//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyShift
    {
        public int shift_id { get; set; }
        public string shift_name { get; set; }
    }
}
