//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptMst
    {
        public int DeptID { get; set; }
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public string Remarks { get; set; }
        public string UpDtUser { get; set; }
        public Nullable<System.DateTime> FeedDt { get; set; }
        public Nullable<System.DateTime> UpDateDt { get; set; }
        public Nullable<System.DateTime> SuncDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
