//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesgMst
    {
        public long Id { get; set; }
        public string DesgCode { get; set; }
        public string DesgDesc { get; set; }
        public Nullable<System.DateTime> SuncDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
