//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEQKARTNewEntities : DbContext
    {
        public SEQKARTNewEntities()
            : base("name=SEQKARTNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual DbSet<WORKER> WORKERs { get; set; }
        public virtual DbSet<AttendanceStatu> AttendanceStatus { get; set; }
        public virtual DbSet<DailyShift> DailyShifts { get; set; }
        public virtual DbSet<AttendanceSource> AttendanceSources { get; set; }
        public virtual DbSet<ProgramMaster> ProgramMasters { get; set; }
        public virtual DbSet<EmpMST> EmpMSTs { get; set; }
        public virtual DbSet<CatgMst> CatgMsts { get; set; }
        public virtual DbSet<DesgMst> DesgMsts { get; set; }
        public virtual DbSet<DeptMst> DeptMsts { get; set; }
    }
}
