//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int serial_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> attendance_date { get; set; }
        public string employee_code { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<int> attendance_source { get; set; }
        public Nullable<int> gate_pass_time { get; set; }
        public Nullable<int> ot_deducton_time { get; set; }
        public Nullable<System.TimeSpan> attendance_in_first { get; set; }
        public Nullable<System.TimeSpan> attendance_out_first { get; set; }
        public Nullable<System.TimeSpan> attendance_in_last { get; set; }
        public Nullable<System.TimeSpan> attendance_out_last { get; set; }
        public Nullable<int> working_hours { get; set; }

        public bool DailyWage { get; set; }

        public int LunchBreak { get; set; }
        public int OT_Extra { get; set; }

        public string status_type { get; set; }
    }
}
