//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramMaster
    {
        public string ProgCode { get; set; }
        public string ProgDesc { get; set; }
        public string ProgInMenu { get; set; }
        public string ProgInMenuGroup { get; set; }
        public string ProgActive { get; set; }
        public string ProgOptsType { get; set; }
        public long ProgAid { get; set; }
        public string ProgProcName { get; set; }
        public string ProgFormLink { get; set; }
        public string ProgNFA { get; set; }
        public string ProCaption { get; set; }
        public string RoleCode { get; set; }
        public string OrderBy { get; set; }
        public string ProgPrinterName { get; set; }
        public Nullable<System.DateTime> SuncDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string ProgRadialTag { get; set; }
        public byte[] ProgSVG1 { get; set; }
        public byte[] ProgSVG2 { get; set; }
        public byte[] ProgSVG3 { get; set; }
        public string ProgSubMainForm { get; set; }
    }
}
