//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqKartLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKER
    {
        public int WRKSYSID { get; set; }
        public Nullable<System.DateTime> WRKSYSDATE { get; set; }
        public string WRKCONTID { get; set; }
        public string WRKID { get; set; }
        public string WRKNAME { get; set; }
        public string WRKFLOORID { get; set; }
        public Nullable<bool> WRKSPECIJOB { get; set; }
        public Nullable<int> WRKSPECIJOBID { get; set; }
        public string WRKBTCHPREFIX { get; set; }
        public string WRKBTCHSUFFIX { get; set; }
        public Nullable<long> WRKBATCHNO { get; set; }
        public Nullable<bool> WRKBTCHANGEOPT { get; set; }
        public string WRKBTCHANGEEVRY { get; set; }
        public string WRKMOBNO { get; set; }
        public string WRKALTMOBNO { get; set; }
        public string WRKEMAILID { get; set; }
        public string WRKIDTYPE { get; set; }
        public string WRKIDNO { get; set; }
        public byte[] WRKIMAGE { get; set; }
        public Nullable<System.DateTime> WRKJNDT { get; set; }
        public Nullable<bool> WRKINACT { get; set; }
        public Nullable<System.DateTime> WRKRJDT { get; set; }
        public string WRKBY { get; set; }
        public string WRKEDTBY { get; set; }
        public Nullable<System.DateTime> WRKEDTON { get; set; }
        public Nullable<System.DateTime> SuncDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
